"""``lawvm.invariant_generator.v0`` — the finite-axis invariant GENERATOR.

WHAT THIS ENABLES — the compounding move made generative (Pro doc
``pro_on_invariant_mining_and_more.md`` §13 step 1: "then generate invariants
from claims"). The :mod:`lawvm.core.claim_surface_manifest` declares WHICH public
claims LawVM makes; :mod:`lawvm.core.invariant_spec` holds the hand/registry-
authored invariant rows that account for them; the coverage gate
(:mod:`tests.test_claim_surface_coverage`) asserts every claim has ≥1 invariant
in an ALLOWED bucket. That gate answers "is there AT LEAST ONE accounting path?"
It does NOT answer the sharper, compounding question this module adds:

    *Given the declared SHAPE of a claim, WHICH KINDS of invariant does that
    shape DEMAND — and is each demanded kind actually discharged by an
    InvariantSpec row?*

A claim whose public sentence says "every ... no ... silently dropped" DEMANDS a
per-unit totality invariant. A claim that names a ``required_root`` DEMANDS an
invariant committing that root. A claim that declares non-guarantees DEMANDS a
boundary invariant. The generator enumerates these OBLIGATIONS from the claim's
declared shape via a fixed question battery, then cross-checks them against the
InvariantSpec rows. An obligation with no discharging invariant is a
:class:`CoverageGap` — a typed finding, not a silent omission.

This is the compounding payoff: a NEW capability becomes ``declare a ClaimSpec``
→ the generator tells you exactly which invariant kinds you owe → you add those
rows → the gate proves coverage. The marginal cost of Integrity on each future
claim drops toward "fill in the obligations the generator names".

THE FINITE AXES (Pro §13). The obligations are generated by crossing the claim
surface against a closed battery of structural questions. v0 implements the
questions that are *structurally* decidable from the declared ClaimSpec shape
(its ``public_sentence`` markers, ``required_roots``, ``allowed_non_guarantees``):

    ACTIVE in v0:
      * TOTALITY            — universal-coverage language ⇒ a per-unit check
      * CLOSURE             — closed-set language ⇒ a membership check/refusal
      * AUTHORITY_FIREWALL  — authority/conformance/replay language ⇒ a firewall
      * ROOT_COMMITMENT     — a named required_root ⇒ an invariant committing it
      * NON_GUARANTEE_COVERAGE — declared non-guarantees ⇒ a boundary invariant.
        This question fires at the CLAIM level (≥1 boundary invariant exists). The
        sharper PER-HANDLE resolution — does each declared non-guarantee HANDLE
        bind to a registered :class:`~lawvm.core.assumption_register.AssumptionRegister`?
        — is no longer deferred: it is checked by
        :mod:`lawvm.core.claim_assumption_binding` (handle → assumption) and gated
        by :mod:`tests.test_claim_assumption_binding`. A NEW handle with no binding
        FAILS that gate.

    DEFERRED (declared, not silently skipped — Pro §12 versioned completeness):
      * CONSERVATION / DETERMINISM / IDENTITY — substrate-global properties
        (canonical-JSON hash profile, named Merkle roots) checked by the
        substrate layer, not per-claim; generating them per-claim would
        manufacture false gaps. Owner: substrate.roots / substrate.canonical_json.
      * PROVENANCE / SCOPE-TIME — require per-object-field introspection beyond
        the declared ClaimSpec shape; deferred to a later generator version with
        an object-field axis.
      * GUARD_LIVENESS — the fire-drill obligation (Pro §13 step 4): an invariant
        carrying a hard/strict finding_code DEMANDS a production fire-drill.
        Deferred to the fire-drill registry; wire in once it lands.

HONESTY BOUNDARY (constructive-invariant pattern). The generator decides
APPLICABILITY from declared-shape markers (a closed, conservative keyword set
that errs toward RAISING an obligation), and decides DISCHARGE from the
structural profile of the claim's invariants (bucket / unit_kind / a marker in
the predicate). A discharged obligation asserts an invariant of the right KIND
EXISTS — NOT that the invariant is semantically correct or complete (that is the
invariant's own ``checker_ref``'s job). v0 ranges over the DECLARED claim surface
at its version; "all obligations" is always "all v0-active obligations for THIS
declared surface". It is a generator of REQUIRED-KIND obligations, not a prover
of invariant correctness.
"""

from __future__ import annotations

from collections.abc import Callable, Sequence
from dataclasses import dataclass

from lawvm.core.claim_surface_manifest import (
    ClaimSpec,
    ClaimSurfaceManifest,
    v0_claim_surface_manifest,
)
from lawvm.core.invariant_spec import (
    InvariantSet,
    InvariantSpec,
    v0_invariant_set,
)
from lawvm.substrate.canonical_json import JsonValue, nfc
from lawvm.substrate.roots import leaf_hash, map_root

_SCHEMA_OBLIGATION = "lawvm.generated_obligation.v0"
_DOMAIN_OBLIGATION = "generated_obligation"
_DOMAIN_OBLIGATION_SET_ROOT = "generated_obligation_set"

#: The generator version. Bumping it widens/changes the active battery.
INVARIANT_GENERATOR_VERSION = "v0"

#: The typed finding code an undischarged obligation raises.
UNDISCHARGED_OBLIGATION_FINDING = "INVARIANT.UNDISCHARGED_OBLIGATION"


class InvariantGeneratorError(ValueError):
    """A generator object violates a v0 schema invariant."""


# --------------------------------------------------------------------------- #
# The closed marker sets — applicability is decided from declared shape.       #
# All matching is case-insensitive substring over NFC-normalized text. The     #
# sets are deliberately conservative: a marker raises an obligation; a missing  #
# marker only means "not REQUIRED here" (a claim may still carry extra          #
# invariants). False-raise costs an explicit discharge; false-omit is the       #
# danger, so the sets favor raising.                                            #
# --------------------------------------------------------------------------- #

# Universal-coverage / totality language ⇒ the claim ranges over a universe of
# units and must not silently drop one ⇒ a per-unit totality invariant.
_TOTALITY_MARKERS: frozenset[str] = frozenset(
    {"every ", "no expected", "silently", "each ", "no external", "all expected"}
)

# Closed-set classification language ⇒ an emitted value lands in a fixed set and
# an out-of-set value must be a typed finding/refusal ⇒ a membership check.
_CLOSURE_MARKERS: frozenset[str] = frozenset(
    {"closed set", "exactly one of", "into the closed", "one of {", "exactly one"}
)

# Authority / conformance / replay language ⇒ the claim touches the authority
# firewall (a projection/surface fact must not become replay/legal-state
# authority) ⇒ an authority-firewall invariant.
_AUTHORITY_MARKERS: frozenset[str] = frozenset(
    {
        "authority",
        "matrix",
        "replay authorization",
        "replay authority",
        "never replay",
        "conformance",
        "legal-state plane",
        "legal_state",
        "grant",
        "forging",
    }
)


# --------------------------------------------------------------------------- #
# Generated objects.                                                           #
# --------------------------------------------------------------------------- #


@dataclass(frozen=True, slots=True)
class GeneratedObligation:
    """One invariant-KIND obligation a claim's declared shape demands.

    * ``claim_id`` — the claim whose shape raised the obligation.
    * ``obligation_id`` — the battery question (TOTALITY / CLOSURE / ...).
    * ``trigger`` — the declared-shape signal that raised it (a marker / root
      name / the fact non-guarantees were declared) — the audit trail of WHY.
    * ``required_profile`` — the invariant profile that discharges it (prose).
    * ``discharged_by`` — the ids of the InvariantSpec rows that discharge it
      (empty ⇒ this obligation is an undischarged :class:`CoverageGap`).
    """

    claim_id: str
    obligation_id: str
    trigger: str
    required_profile: str
    discharged_by: tuple[str, ...] = ()

    @property
    def discharged(self) -> bool:
        return len(self.discharged_by) > 0

    def to_canonical_dict(self) -> dict[str, JsonValue]:
        return {
            "schema": _SCHEMA_OBLIGATION,
            "claim_id": nfc(self.claim_id),
            "obligation_id": nfc(self.obligation_id),
            "trigger": nfc(self.trigger),
            "required_profile": nfc(self.required_profile),
            "discharged_by": list(self.discharged_by),
        }

    @property
    def obligation_body_hash(self) -> str:
        return leaf_hash(_DOMAIN_OBLIGATION, self.to_canonical_dict())


@dataclass(frozen=True, slots=True)
class CoverageGap:
    """An obligation a claim's shape demands but no InvariantSpec discharges.

    A typed finding (``INVARIANT.UNDISCHARGED_OBLIGATION``), never a silent
    omission — the generator's whole point.
    """

    claim_id: str
    obligation_id: str
    detail: str
    finding_code: str = UNDISCHARGED_OBLIGATION_FINDING


@dataclass(frozen=True, slots=True)
class GenerationResult:
    """The generator's output over a (manifest, invariant set) pair."""

    obligations: tuple[GeneratedObligation, ...]
    generator_version: str = INVARIANT_GENERATOR_VERSION
    claim_surface_version: str = "v0"

    @property
    def gaps(self) -> tuple[CoverageGap, ...]:
        """The undischarged obligations as typed coverage-gap findings."""
        return tuple(
            CoverageGap(
                claim_id=ob.claim_id,
                obligation_id=ob.obligation_id,
                detail=(
                    f"claim {ob.claim_id!r} shape raised obligation "
                    f"{ob.obligation_id!r} ({ob.trigger}) but no InvariantSpec row "
                    f"discharges it; required: {ob.required_profile}"
                ),
            )
            for ob in self.obligations
            if not ob.discharged
        )

    @property
    def is_fully_discharged(self) -> bool:
        return len(self.gaps) == 0

    def for_claim(self, claim_id: str) -> tuple[GeneratedObligation, ...]:
        return tuple(ob for ob in self.obligations if ob.claim_id == claim_id)

    @property
    def obligation_set_root(self) -> str:
        """``MapRoot`` over ``{claim_id|obligation_id: body_hash}`` — committable."""
        return map_root(
            _DOMAIN_OBLIGATION_SET_ROOT,
            {
                f"{ob.claim_id}|{ob.obligation_id}": ob.obligation_body_hash
                for ob in self.obligations
            },
        )

    def __len__(self) -> int:
        return len(self.obligations)


# --------------------------------------------------------------------------- #
# The question battery — one ObligationRule per active axis.                   #
#                                                                              #
# A rule is a pure pair of functions over (claim) and (claim, its invariants): #
#   * ``trigger`` returns a non-empty rationale string IF the claim's declared #
#     shape raises this obligation, else "" (not applicable).                  #
#   * ``discharge`` returns the ids of the invariants that satisfy the required #
#     profile (empty ⇒ gap). It is only consulted when ``trigger`` fired.      #
# --------------------------------------------------------------------------- #


@dataclass(frozen=True, slots=True)
class ObligationRule:
    obligation_id: str
    required_profile: str
    trigger: Callable[[ClaimSpec], str]
    discharge: Callable[[ClaimSpec, tuple[InvariantSpec, ...]], tuple[str, ...]]


def _claim_text(claim: ClaimSpec) -> str:
    """The lowercased declared-shape text the markers scan (sentence + handles)."""
    parts = [claim.public_sentence, *claim.allowed_non_guarantees]
    return nfc(" ".join(parts)).lower()


def _first_marker(text: str, markers: frozenset[str]) -> str:
    for marker in sorted(markers):
        if marker in text:
            return marker
    return ""


# --- TOTALITY -------------------------------------------------------------- #
def _trigger_totality(claim: ClaimSpec) -> str:
    marker = _first_marker(_claim_text(claim), _TOTALITY_MARKERS)
    return f"universal-coverage language ({marker!r})" if marker else ""


def _discharge_totality(
    claim: ClaimSpec, invs: tuple[InvariantSpec, ...]
) -> tuple[str, ...]:
    return tuple(
        inv.id
        for inv in invs
        if inv.unit_kind == "per-unit"
        and inv.bucket in {"implemented_check", "projection_verifier", "checker_step"}
    )


# --- CLOSURE --------------------------------------------------------------- #
def _trigger_closure(claim: ClaimSpec) -> str:
    marker = _first_marker(_claim_text(claim), _CLOSURE_MARKERS)
    return f"closed-set classification language ({marker!r})" if marker else ""


def _discharge_closure(
    claim: ClaimSpec, invs: tuple[InvariantSpec, ...]
) -> tuple[str, ...]:
    # A closed set is enforced by a live check that emits a typed out-of-set
    # finding, OR by a writer/checker refusal.
    return tuple(
        inv.id
        for inv in invs
        if (inv.bucket == "implemented_check" and inv.finding_code)
        or inv.bucket in {"writer_refusal", "checker_step"}
    )


# --- AUTHORITY_FIREWALL ---------------------------------------------------- #
def _trigger_authority(claim: ClaimSpec) -> str:
    marker = _first_marker(_claim_text(claim), _AUTHORITY_MARKERS)
    return f"authority/conformance/replay language ({marker!r})" if marker else ""


def _discharge_authority(
    claim: ClaimSpec, invs: tuple[InvariantSpec, ...]
) -> tuple[str, ...]:
    # Discharged by any allowed-bucket invariant whose predicate engages the
    # authority firewall (the matrix / the not-replay-authority boundary).
    return tuple(
        inv.id
        for inv in invs
        if inv.is_allowed and _first_marker(nfc(inv.predicate).lower(), _AUTHORITY_MARKERS)
    )


# --- ROOT_COMMITMENT ------------------------------------------------------- #
def _trigger_root(claim: ClaimSpec) -> str:
    return (
        f"declares required_roots {list(claim.required_roots)!r}"
        if claim.required_roots
        else ""
    )


def _discharge_root(
    claim: ClaimSpec, invs: tuple[InvariantSpec, ...]
) -> tuple[str, ...]:
    # EVERY declared required_root must be committed by some invariant's
    # root_membership; if any is uncommitted the obligation is undischarged.
    committed = {inv.root_membership for inv in invs if inv.root_membership}
    if all(root in committed for root in claim.required_roots):
        return tuple(
            inv.id
            for inv in invs
            if inv.root_membership in set(claim.required_roots)
        )
    return ()


# --- NON_GUARANTEE_COVERAGE ------------------------------------------------ #
def _trigger_non_guarantee(claim: ClaimSpec) -> str:
    return (
        f"declares {len(claim.allowed_non_guarantees)} non-guarantee(s)"
        if claim.allowed_non_guarantees
        else ""
    )


def _discharge_non_guarantee(
    claim: ClaimSpec, invs: tuple[InvariantSpec, ...]
) -> tuple[str, ...]:
    return tuple(
        inv.id
        for inv in invs
        if inv.bucket
        in {"declared_non_guarantee", "declared_residual", "deferred_with_owner"}
    )


#: The v0 active question battery.
V0_BATTERY: tuple[ObligationRule, ...] = (
    ObligationRule(
        obligation_id="TOTALITY",
        required_profile=(
            "a per-unit invariant in an implemented_check / projection_verifier / "
            "checker_step bucket (no expected unit silently dropped)"
        ),
        trigger=_trigger_totality,
        discharge=_discharge_totality,
    ),
    ObligationRule(
        obligation_id="CLOSURE",
        required_profile=(
            "an implemented_check emitting a typed out-of-set finding, or a "
            "writer_refusal / checker_step enforcing the closed set"
        ),
        trigger=_trigger_closure,
        discharge=_discharge_closure,
    ),
    ObligationRule(
        obligation_id="AUTHORITY_FIREWALL",
        required_profile=(
            "an allowed-bucket invariant engaging the authority firewall "
            "(matrix legality / not-replay-authority / not-conformance boundary)"
        ),
        trigger=_trigger_authority,
        discharge=_discharge_authority,
    ),
    ObligationRule(
        obligation_id="ROOT_COMMITMENT",
        required_profile=(
            "for EACH declared required_root, an invariant whose root_membership "
            "commits that root"
        ),
        trigger=_trigger_root,
        discharge=_discharge_root,
    ),
    ObligationRule(
        obligation_id="NON_GUARANTEE_COVERAGE",
        required_profile=(
            "a declared_non_guarantee / declared_residual / deferred_with_owner "
            "invariant bounding the claim"
        ),
        trigger=_trigger_non_guarantee,
        discharge=_discharge_non_guarantee,
    ),
)


# --------------------------------------------------------------------------- #
# The generator.                                                               #
# --------------------------------------------------------------------------- #


def generate_obligations(
    manifest: ClaimSurfaceManifest,
    invariant_set: InvariantSet,
    *,
    battery: Sequence[ObligationRule] = V0_BATTERY,
) -> GenerationResult:
    """Generate the invariant-kind obligations the claim surface demands.

    For each claim × each battery rule whose ``trigger`` fires (the claim's
    declared shape raises the obligation), emit a :class:`GeneratedObligation`
    carrying the ids of the invariants that discharge it (empty ⇒ a gap).
    Deterministic: claims in manifest order, rules in battery order.
    """
    if manifest.claim_surface_version != invariant_set.claim_surface_version:
        raise InvariantGeneratorError(
            "claim-surface version mismatch: manifest "
            f"{manifest.claim_surface_version!r} vs invariant set "
            f"{invariant_set.claim_surface_version!r} — the generator joins a "
            f"surface to ITS invariant set (Pro §12 versioned completeness)"
        )
    obligations: list[GeneratedObligation] = []
    for claim in manifest.claims:
        claim_invs = invariant_set.for_claim(claim.claim_id)
        for rule in battery:
            trigger = rule.trigger(claim)
            if not trigger:
                continue
            discharged_by = rule.discharge(claim, claim_invs)
            obligations.append(
                GeneratedObligation(
                    claim_id=claim.claim_id,
                    obligation_id=rule.obligation_id,
                    trigger=trigger,
                    required_profile=rule.required_profile,
                    discharged_by=discharged_by,
                )
            )
    return GenerationResult(
        obligations=tuple(obligations),
        generator_version=INVARIANT_GENERATOR_VERSION,
        claim_surface_version=manifest.claim_surface_version,
    )


def generate_v0_obligations() -> GenerationResult:
    """Run the generator over the live v0 claim surface + invariant set."""
    return generate_obligations(v0_claim_surface_manifest(), v0_invariant_set())


__all__ = [
    "INVARIANT_GENERATOR_VERSION",
    "UNDISCHARGED_OBLIGATION_FINDING",
    "V0_BATTERY",
    "CoverageGap",
    "GeneratedObligation",
    "GenerationResult",
    "InvariantGeneratorError",
    "ObligationRule",
    "generate_obligations",
    "generate_v0_obligations",
]
