"""The johtolause structural-noun core forms are M1-engine-derived, not enumerated.

The structural-noun LEMMAS stay closed (genuine semantic anchors); their NOM/GEN/
ILL inflected forms are generated by the M1 morphology engine over the closed
``heads`` table rather than hand-written.  These tests pin the contract so a
future engine change cannot silently drop a historically-recognized structural
surface, and so the derivation never accidentally introduces a new surface that
would change tokenization behaviour.
"""

from __future__ import annotations

from lawvm.finland.johtolause.lexicon import (
    _DERIVED_STRUCTURAL_HEADS,
    _DERIVED_STRUCTURAL_SURFACES,
    _VOCAB,
)
from lawvm.finland.morphology import generate_forms, head_entry
from lawvm.finland.morphology.api import MorphCase, MorphNumber
from lawvm.finland.morphology.heads import is_known_head

# The historically hand-enumerated NOM/GEN/ILL surfaces for the derived heads.
# This is the invariant the engine must keep reproducing: a future paradigm
# change that stopped generating one of these would silently break tokenization
# of the most common amendment-target shapes.
_HISTORICAL_CORE_FORMS: dict[str, tuple[tuple[str, str], ...]] = {
    "luku": (("luku", "NOM"), ("luvun", "GEN"), ("lukuun", "ILL")),
    "momentti": (("momentti", "NOM"), ("momentin", "GEN"), ("momenttiin", "ILL")),
    "kohta": (("kohta", "NOM"), ("kohdan", "GEN"), ("kohtaan", "ILL")),
}


def test_derived_heads_are_closed_known_heads() -> None:
    """Every derived structural lemma is a closed M1 head (never guessed)."""
    for lemma in _DERIVED_STRUCTURAL_HEADS:
        assert is_known_head(lemma), lemma


def test_historical_core_forms_are_present_with_correct_tag() -> None:
    """Each historically-evidenced NOM/GEN/ILL surface is in ``_VOCAB`` with its
    original (lemma, cat, case) — the strict-superset / no-silent-drop guarantee.
    """
    for lemma, forms in _HISTORICAL_CORE_FORMS.items():
        cat = _DERIVED_STRUCTURAL_HEADS[lemma]
        for surface, case in forms:
            assert surface in _VOCAB, (lemma, surface)
            got_lemma, got_cat, got_case, _vc = _VOCAB[surface]
            assert (got_lemma, got_cat, got_case) == (lemma, cat, case), (
                surface,
                (got_lemma, got_cat, got_case),
            )
            assert surface in _DERIVED_STRUCTURAL_SURFACES, surface


def test_derivation_matches_engine_output_exactly() -> None:
    """The registered surfaces are exactly the engine's deterministic NOM/GEN/ILL
    output for the closed heads — no manual surface crept into the derived set.
    """
    expected: set[str] = set()
    for lemma in _DERIVED_STRUCTURAL_HEADS:
        forms = generate_forms(
            head_entry(lemma),
            cases=(MorphCase.NOM, MorphCase.GEN, MorphCase.ILL),
            numbers=(MorphNumber.SG,),
        )
        for form in forms:
            assert form.certainty == "deterministic", (lemma, form.case.name)
            expected.add(form.surface.lower())
    assert _DERIVED_STRUCTURAL_SURFACES == expected


def test_derivation_introduces_no_new_surface() -> None:
    """Every engine-derived surface coincides with a historically-evidenced one:
    the change is provenance-only, so tokenization behaviour is unchanged.
    """
    historical = {
        surface.lower()
        for forms in _HISTORICAL_CORE_FORMS.values()
        for surface, _case in forms
    }
    assert _DERIVED_STRUCTURAL_SURFACES == historical
