"""lawvm scaffold - generate a blocked, contract-first jurisdiction starter.

Usage:
    lawvm scaffold <jurisdiction>

The generated package is intentionally non-executing. It creates a local
adapter shell that can emit blocked P5 clause-surface artifacts for inventoried
source units, but it does not parse clauses, lower payloads, apply operations,
or claim replay support.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path


_STARTER_TMPL = '''\
"""{display} contract-first starter for LawVM.

This module is a transparency bridge, not a replay frontend. It preserves
inventoried amendment source units as blocked P5 clause-surface evidence until
the jurisdiction has source-backed parsing, payload, lowering, and replay
phases.
"""
from __future__ import annotations

from collections.abc import Iterable

from jurisdiction_starter.p5_runtime_scaffold import (
    StarterP5RuntimeScaffold,
    StarterP5SourceUnit,
    build_blocked_p5_runtime_scaffold,
)


FRONTEND_ID = "{jur}"


def build_blocked_clause_surface(
    *,
    run_id: str,
    source_id: str,
    source_units: Iterable[StarterP5SourceUnit],
    base_id: str | None = None,
) -> StarterP5RuntimeScaffold:
    """Emit explicit non-claim P5 evidence for inventoried source units.

    This helper deliberately reports zero accepted operation/effect rows and
    zero replay attempts. Replace it only after the frontend has real,
    source-backed P5 parsing and lowering.
    """

    return build_blocked_p5_runtime_scaffold(
        frontend_id=FRONTEND_ID,
        run_id=run_id,
        source_id=source_id,
        base_id=base_id,
        source_units=source_units,
    )
'''


_INIT_TMPL = '''\
"""{display} LawVM starter package.

Generated by `lawvm scaffold`. This package exposes only blocked P5 evidence
scaffolding and does not claim replay support.
"""
from lawvm.{jur}.starter import FRONTEND_ID, build_blocked_clause_surface

__all__ = ["FRONTEND_ID", "build_blocked_clause_surface"]
'''


_TEST_TMPL = '''\
"""Generated smoke tests for the {display} starter package.

Run from the LawVM checkout after generation:
    uv run python src/lawvm/{jur}/test_{jur}.py
"""
from __future__ import annotations

import sys

from jurisdiction_starter.p5_runtime_scaffold import StarterP5SourceUnit


def test_blocked_clause_surface_is_non_claim() -> None:
    from lawvm.{jur}.starter import FRONTEND_ID, build_blocked_clause_surface

    artifact = build_blocked_clause_surface(
        run_id="run-1",
        source_id="source-1",
        base_id="base-1",
        source_units=(
            StarterP5SourceUnit(
                source_artifact_id="source-1.xml",
                source_unit_id="unit-1",
                source_locator="xml:/act/body/section[1]",
                raw_text="Example operative-looking text.",
            ),
        ),
    )

    assert FRONTEND_ID == "{jur}"
    assert artifact.evidence_pack_summary["claim_summary"]["operation_effect_rows"] == 0
    assert artifact.evidence_pack_summary["claim_summary"]["replay_attempts"] == 0
    assert artifact.findings[0]["strict_disposition"] == "block"


if __name__ == "__main__":
    test_blocked_clause_surface_is_non_claim()
    print("PASS blocked non-claim starter")
    sys.exit(0)
'''


_README_TMPL = '''\
# {display} LawVM Starter

This generated package is a blocked, contract-first starter. It does not parse
clauses, lower operations, apply amendments, or claim replay support.

The only generated runtime helper is `build_blocked_clause_surface(...)`, which
wraps inventoried amendment source units in explicit blocked P5 evidence rows.

Next steps:

1. Fill out `jurisdiction_starter/` evidence-surface questions for this source
   regime.
2. Write source acquisition and inventory code before parsing operative text.
3. Replace blocked P5 rows only when a source-backed clause parser exists.
4. Add findings, strict-mode behavior, and regression tests for every recovery.
'''


def _validate_jurisdiction(name: str) -> str:
    """Return lower-case snake_case name or raise ValueError."""

    cleaned = re.sub(r"[^a-z0-9_]", "", name.lower().replace("-", "_"))
    if not cleaned or re.match(r"^[a-z]", cleaned) is None:
        raise ValueError(f"Invalid jurisdiction name: {name!r} (must start with a letter, a-z/0-9/_ only)")
    return cleaned


def scaffold(jurisdiction: str, src_root: Path) -> None:
    """Create a blocked jurisdiction starter under src_root/lawvm/<jurisdiction>/."""

    jur = _validate_jurisdiction(jurisdiction)
    display = jurisdiction.replace("_", " ").replace("-", " ").title()

    dest = src_root / "lawvm" / jur
    if dest.exists():
        print(f"ERROR: {dest} already exists. Delete it first or choose a different name.", file=sys.stderr)
        sys.exit(1)

    dest.mkdir(parents=True)
    files = {
        "__init__.py": _INIT_TMPL.format(jur=jur, display=display),
        "starter.py": _STARTER_TMPL.format(jur=jur, display=display),
        f"test_{jur}.py": _TEST_TMPL.format(jur=jur, display=display),
        "README.md": _README_TMPL.format(jur=jur, display=display),
    }
    for filename, content in files.items():
        path = dest / filename
        path.write_text(content, encoding="utf-8")
        print(f"  created  {path}")

    print(f"\nBlocked starter created: {dest}")
    print("Next steps:")
    print("  1. Inventory source units; do not parse or replay yet.")
    print(f"  2. Run: cd LawVM && uv run python src/lawvm/{jur}/test_{jur}.py")
    print("  3. Use jurisdiction_starter/ to document source surfaces and phase gates.")


def main(args) -> None:
    src_root = Path(__file__).parents[2]
    scaffold(args.jurisdiction, src_root)
