"""UK spec-ledger rule metadata: the S/P sort (§3.5) and per-rule falsifier (§3.2(4)).

READ-ONLY / ADDITIVE (mirrors the FI meta sidecar). The UK catalog
(``spec_ledger_uk_catalog`` + supplement) is large (hundreds of witness ids), so the
S/P sort is derived by a principled *classifier* over the id (rather than a hand-written
line per id), and falsifiers are authored by *layer template* keyed off the same
classification. Both are computed from the merged catalog keys the adapter already loads,
so they can never drift out of coverage with the believed_spec catalog: every catalogued
id gets a role and a falsifier by construction.

S/P classification for UK (see ``notes_internal/FABLE_SPEC_RECONSTRUCTION.md`` §3.5):

* **P (compiler-survival policy)** — ids whose behaviour is about THIS compiler surviving
  its own coverage gaps or reconciling with the oracle, not about UK legislative
  semantics:
    - ``uk_manual_frontier_*`` / ``uk_manual_compile_frontier_*`` (typed
      "do-not-lower-deterministically" verdicts — the negative-spec frontier);
    - ``uk_replay_*`` (replay-time target *resolution* tolerance: recursive descent,
      anchor normalization, *_unresolved deferrals);
    - ``uk_oracle_*`` / ``*_elided`` / ``*_preserved`` / ``*_normalized`` /
      ``*_realigned`` / ``*_retargeted`` / ``*_inferred`` / ``*_refined`` /
      ``*_rebound`` (oracle-alignment, editorial elision, and target-repair policies);
    - ``*_claim_validated|rejected*|withheld*`` and ``*_finding`` (the manual-claim
      gate machinery — a compiler mechanism for admitting human claims);
    - ``overlay_default_replay_authorized_false`` (a firewall audit rule).
* **S (law-hypothesis)** — everything else: the ``uk_effect_*`` amendment-instruction
  grammar (substitution/insertion/omission/repeal-table/table/definition families),
  temporal semantics (``uk_effect_temporal_*``, ``uk_commencement_*``,
  ``uk_prospective_*``), and the ``uk_section_renumber_relabel`` migration-naming rule —
  each a statement about what UK drafting language *means*.
"""
from __future__ import annotations

from typing import Dict, Literal

RuleRole = Literal["S", "P"]

# --- id substrings / prefixes / suffixes that mark a P (compiler-survival) rule ---
_UK_P_PREFIXES = (
    "uk_manual_frontier_",
    "uk_manual_compile_frontier_",
    "uk_replay_",
    "uk_oracle_",
    "overlay_default_replay_authorized_false",
)
_UK_P_SUFFIXES = (
    "_unresolved",
    "_rejected",
    "_preserved",
    "_elided",
    "_normalized",
    "_realigned",
    "_retargeted",
    "_inferred",
    "_refined",
    "_rebound",
    "_withheld_unvalidated",
)
# substrings appearing mid-id (claim-gate machinery, target-repair policies)
_UK_P_SUBSTRINGS = (
    "_claim_validated",
    "_claim_rejected",
    "_finding",
    "_withheld",
    "_target_normalized",
    "_target_refined",
    "_target_rebound",
    "_eid_alignment",
    "_eid_synthesis",
    "_preimage_gap",
    "_chain_gap",
    "_target_source_gap",
    "_deferred_to_base",
)


def classify_uk_rule_role(rule_id: str) -> RuleRole:
    """Return ``"P"`` for a compiler-survival policy id, else ``"S"``.

    Pure function of the id string, so the classification is stable and auditable and
    covers every catalogued id (including ids minted after this module was written).
    """
    for pref in _UK_P_PREFIXES:
        if rule_id.startswith(pref):
            return "P"
    for suf in _UK_P_SUFFIXES:
        if rule_id.endswith(suf):
            return "P"
    for sub in _UK_P_SUBSTRINGS:
        if sub in rule_id:
            return "P"
    return "S"


# A few hand-authored falsifiers for the highest-value / most-cited UK rules; the rest
# are generated by template. Hand entries win over the template.
_UK_RULE_FALSIFIERS_SEED: Dict[str, str] = {
    "uk_effect_bare_quoted_substitution_text_patch": (
        "An oracle EID where 'for \"X\" substitute \"Y\"' fired but the consolidated "
        "text does not show X replaced by Y at the target."
    ),
    "uk_effect_simple_whole_act_all_occurrences_substitution_text_patch": (
        "An oracle EID where 'In this Act, for X substitute Y' fired but some occurrence "
        "of X across the Act is un-rewritten (or a non-occurrence was rewritten) in the "
        "consolidated text."
    ),
    "uk_effect_quoted_word_ordinal_places_substitution_text_patch": (
        "An oracle EID where the ordinal-place substitution rewrote an occurrence OTHER "
        "than the named ordinal place(s) in the consolidated text."
    ),
    "uk_effect_after_child_text_insertion_patch": (
        "An oracle EID where 'after \"X\" insert \"Y\"' fired but Y is absent or placed "
        "somewhere other than immediately after child text X."
    ),
    "uk_effect_repeal_table_structural_repeal": (
        "An oracle EID where a repeal-table whole-provision row fired but the named "
        "provision is still present in the consolidated text."
    ),
    "uk_effect_temporal_ceases_to_have_effect_replay_excluded": (
        "An oracle EID where a future-dated 'ceases to have effect' was applied to the "
        "current text (or a due one was not excluded) versus the consolidated PIT."
    ),
    "uk_section_renumber_relabel": (
        "A UK RENUMBER whose WriteReceipt migration is unnamed (audits as a violation, "
        "not qualified) despite a source->destination label divergence."
    ),
}

# Layer-template falsifiers keyed off the classifier: S = "form fired, consolidated text
# does not show its predicted effect"; P = "the recovered/tolerant/frontier decision
# contradicts the consolidated text at a rate exceeding tolerance (only statistically
# falsifiable)".
_S_FALSIFIER_TEMPLATE = (
    "An oracle EID where {rid} fired but the consolidated text does not exhibit the "
    "transformation its believed_spec predicts (the drafting form denotes a different "
    "effect)."
)
_P_FALSIFIER_TEMPLATE = (
    "A rate of oracle EIDs where {rid}'s recovery/tolerance/frontier decision contradicts "
    "the consolidated text exceeding tolerance (a compiler-survival policy is only "
    "statistically falsifiable)."
)


def build_uk_rule_roles(catalog_ids: "Dict[str, str] | frozenset[str] | set[str]") -> Dict[str, RuleRole]:
    """S/P role per catalogued UK rule id, computed from the classifier."""
    return {rid: classify_uk_rule_role(rid) for rid in catalog_ids}


def build_uk_rule_falsifiers(
    catalog_ids: "Dict[str, str] | frozenset[str] | set[str]",
) -> Dict[str, str]:
    """Falsifier per catalogued UK rule id: hand-authored seed, else layer template."""
    out: Dict[str, str] = {}
    for rid in catalog_ids:
        if rid in _UK_RULE_FALSIFIERS_SEED:
            out[rid] = _UK_RULE_FALSIFIERS_SEED[rid]
            continue
        template = (
            _P_FALSIFIER_TEMPLATE
            if classify_uk_rule_role(rid) == "P"
            else _S_FALSIFIER_TEMPLATE
        )
        out[rid] = template.format(rid=rid)
    return out
