"""Governed atom enums for the Finland rulebook scaffold."""

from __future__ import annotations

from enum import StrEnum


class ClauseAtom(StrEnum):
    SECTION_REF = "SECTION_REF"
    MOMENTTI_LIST_GEN = "MOMENTTI_LIST_GEN"
    KOHTA_LIST_GEN = "KOHTA_LIST_GEN"
    BACKREF_SINGULAR = "BACKREF_SINGULAR"
    JOHD = "JOHD"
    JOLLOIN_RENUMBER_PAIR = "JOLLOIN_RENUMBER_PAIR"
    LUKUUNOTTAMATTA = "LUKUUNOTTAMATTA"


class PayloadAtom(StrEnum):
    SECTION_WITH_OMISSION = "SECTION_WITH_OMISSION"
    DIRECT_LETTERED_SUBITEM_RUN = "DIRECT_LETTERED_SUBITEM_RUN"
    TABLE_WITH_NAMED_ROWS = "TABLE_WITH_NAMED_ROWS"
    SPARSE_SUBSECTION_BODY = "SPARSE_SUBSECTION_BODY"
    INTRO_LIST_CONTINUATION = "INTRO_LIST_CONTINUATION"
    UNCLAIMED_NONOMISSION_SIBLINGS = "UNCLAIMED_NONOMISSION_SIBLINGS"


class TemporalAtom(StrEnum):
    COMMENCEMENT_WORD = "COMMENCEMENT_WORD"
    EXPIRY_WORD = "EXPIRY_WORD"
    DEFERRED_COMMENCEMENT_WORD = "DEFERRED_COMMENCEMENT_WORD"
    TEMPORAL_WORD = "TEMPORAL_WORD"
    INSERT_TARGET_CLUSTER = "INSERT_TARGET_CLUSTER"
    PHASED_ACTIVATION_WORD = "PHASED_ACTIVATION_WORD"


class SourceAtom(StrEnum):
    EDITORIAL_HEADING_NOISE = "EDITORIAL_HEADING_NOISE"
    EDITORIAL_KUMOTTU_BANNER = "EDITORIAL_KUMOTTU_BANNER"
    EDITORIAL_SOURCE_TAG_RECLASSIFICATION = "EDITORIAL_SOURCE_TAG_RECLASSIFICATION"
    IMPOSSIBLE_SUBSECTION_NUMBERING = "IMPOSSIBLE_SUBSECTION_NUMBERING"
    SCHEMA_INVALID_BODY = "SCHEMA_INVALID_BODY"


class CompareAtom(StrEnum):
    ORACLE_REPEAL_NOTICE_TEXT = "ORACLE_REPEAL_NOTICE_TEXT"
    ORACLE_HTML_XML_TOPOLOGY_DRIFT = "ORACLE_HTML_XML_TOPOLOGY_DRIFT"
    ORACLE_OMISSION_BLANK = "ORACLE_OMISSION_BLANK"
    ORACLE_STALE_SOURCE = "ORACLE_STALE_SOURCE"
    REPLAY_REPEAL_PLACEHOLDER = "REPLAY_REPEAL_PLACEHOLDER"
