"""Neutral output types for the Finnish morphology rule engine (M1).

The engine is generation-first: given a :class:`MorphEntry` (lemma + morph_class
+ flags) it generates the ``reference_v1`` case forms.  Every generated form is a
:class:`MorphForm` carrying a ``rule_id`` and a typed ``certainty`` --- there is
no probabilistic confidence in control flow.

Clitics (``-kin``/``-kaan``/``-han``) and possessive suffixes are an OUTER
token-stripper layer and are explicitly OUT OF SCOPE for M1.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum


class MorphCase(Enum):
    """Finnish grammatical cases generated by the ``reference_v1`` profile."""

    NOM = "nominative"
    GEN = "genitive"
    PART = "partitive"
    INE = "inessive"
    ELA = "elative"
    ILL = "illative"
    ADE = "adessive"
    ABL = "ablative"
    ALL = "allative"
    TRA = "translative"


class MorphNumber(Enum):
    """Grammatical number."""

    SG = "singular"
    PL = "plural"


# ``reference_v1`` case profile (Pro r2): sg has the full ten-case series; pl is
# restricted to the five that carry corpus evidence.
REFERENCE_V1_SG: tuple[MorphCase, ...] = (
    MorphCase.NOM,
    MorphCase.GEN,
    MorphCase.PART,
    MorphCase.INE,
    MorphCase.ELA,
    MorphCase.ILL,
    MorphCase.ADE,
    MorphCase.ABL,
    MorphCase.ALL,
    MorphCase.TRA,
)
REFERENCE_V1_PL: tuple[MorphCase, ...] = (
    MorphCase.NOM,
    MorphCase.GEN,
    MorphCase.PART,
    MorphCase.INE,
    MorphCase.ELA,
)


@dataclass(frozen=True, slots=True)
class MorphForm:
    """A single generated (or classified) word form.

    ``source`` records how the surface was produced; ``certainty`` is the typed
    control-flow signal --- ``deterministic`` for rule output, ``unsupported``
    for a form the engine declines to commit to (fail-loud).
    """

    surface: str
    lemma_id: str
    lemma: str
    case: MorphCase
    number: MorphNumber
    rule_id: str
    source: str = "rule"  # rule | exception | table | alias
    certainty: str = "deterministic"  # deterministic | unsupported


@dataclass(frozen=True, slots=True)
class MorphEntry:
    """An inflectable lexical entry: a lemma plus its small flag set.

    The flags --- not form tables --- are the entire irreducible "vocabulary":

    * ``morph_class`` --- the emergent paradigm key (e.g. ``"-Us->-Ukse-"``).
    * ``gradation`` --- whether consonant gradation *occurs* for this lemma.
    * ``single_k`` --- the lexical k->(zero|v|j) realization (``Turku->Turun``).
    * ``locative_series`` --- ``"internal"`` (-ssa/-lla, default) or
      ``"external"`` (-lla as the *only* locative series, e.g. ``Tampereella``).
    * ``form_overrides`` --- per-(case, number) escape hatch, last resort only.
    """

    lemma_id: str
    lemma: str
    referent_kind: str  # statute_head | agency | place | structural | common
    morph_class: str
    head: str | None = None
    gradation: bool = False
    single_k: str | None = None  # "zero" | "v" | "j"
    locative_series: str = "internal"  # internal | external
    form_overrides: dict[tuple[MorphCase, MorphNumber], str] = field(
        default_factory=dict,
    )


__all__ = [
    "REFERENCE_V1_PL",
    "REFERENCE_V1_SG",
    "MorphCase",
    "MorphEntry",
    "MorphForm",
    "MorphNumber",
]
