"""Reverse-morphology LEMMA INDEX by INVERTING M1 generation.

M1 (:mod:`lawvm.finland.morphology`) is generation-only by design: given a lemma
(via a :class:`~lawvm.finland.morphology.api.MorphEntry`) it produces the
``reference_v1`` inflected forms.  There is deliberately no general
surface -> lemma analyzer (open-world Finnish morphology is not vendored here).

This module builds a SOUND reverse analyzer for the CLOSED, KNOWN legal
vocabulary by enumerating every inflected form of every supplied lemma and
indexing them ``normalized_surface -> {lemmas}``.  Because M1 generation is a
pure deterministic function and the lemma set is closed and finite, the
inversion is exact: ``analyze(surface)`` returns precisely the lemmas whose
M1 paradigm contains ``surface``.

SOUNDNESS BOUNDARY (explicit, non-negotiable):
    * This is reverse analysis ONLY for the closed set of lemmas fed into
      :func:`build_lemma_index`.  A surface that is not generated by any lemma
      in that set returns the EMPTY tuple --- it is *unknown* (out of the closed
      vocabulary), NOT guessed.  The index never attempts open-world analysis.
    * The inversion is sound exactly because generation is deterministic and the
      lemma set is closed: every key in the map is a real M1 output, and the
      complete paradigm of every lemma is enumerated, so a hit is a proof that
      M1 inflects that lemma to that surface, and a miss is a proof that no
      lemma in the set does.
    * Ambiguity is surfaced, never resolved: when two lemmas in the set share an
      inflected surface, :meth:`LemmaIndex.analyze` returns BOTH (fail-loud);
      :meth:`LemmaIndex.lemma_of` returns ``None`` rather than picking one.

Determinism: the index is a pure function of (lemma set, M1 generation).  No
``Date``, no randomness; all outputs are sorted and stable.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from functools import lru_cache
from typing import TYPE_CHECKING

from .api import MorphNumber
from .generate import generate_forms
from .heads import _HEADS, head_entry

if TYPE_CHECKING:
    from collections.abc import Iterable, Mapping

    from .api import MorphEntry


def _normalize(surface: str) -> str:
    """Normalize a surface for indexing/lookup: casefold + strip.

    Casefold (not ``lower``) so the index round-trips Finnish forms robustly;
    strip removes incidental surrounding whitespace.
    """
    return surface.strip().casefold()


@dataclass(frozen=True, slots=True)
class LemmaIndex:
    """A reverse map ``normalized_surface -> sorted lemmas`` over a closed set.

    Build via :func:`build_lemma_index`.  The map only contains surfaces that
    M1 actually generates for the supplied lemmas; everything else is unknown.
    """

    _map: Mapping[str, tuple[str, ...]]
    lemmas: tuple[str, ...]

    def analyze(self, surface: str) -> tuple[str, ...]:
        """Return the lemma(s) whose M1 inflection produces ``surface``.

        Fail-loud on ambiguity: returns ALL matching lemmas (sorted), never a
        single ranked pick.  An empty tuple means ``surface`` is outside the
        closed vocabulary (honest unknown, not a guess).
        """
        return self._map.get(_normalize(surface), ())

    def fingerprint(self) -> str:
        """A stable hex digest identifying this index's closed vocabulary.

        The digest is taken over the FULL inversion behaviour --- every
        ``normalized_surface -> sorted lemmas`` entry --- not just the lemma
        list, so it changes iff the actual analyzer behaviour changes (a lemma
        added/removed, or M1 generation altered such that the paradigm shifts).

        This is the absence-of-annotation anchor: a consumer that records this
        fingerprint alongside an overlay can detect that it is reading an
        ABSENT annotation against a DIFFERENT (e.g. extended) vocabulary than
        the one it expected, so "token analyzed, no lemma" never silently
        becomes a stale negative fact. Deterministic: a pure function of the
        sorted map contents.
        """
        h = hashlib.sha256()
        for surface in sorted(self._map):
            h.update(surface.encode("utf-8"))
            h.update(b"\x00")
            for lemma in self._map[surface]:
                h.update(lemma.encode("utf-8"))
                h.update(b"\x00")
            h.update(b"\x01")
        return h.hexdigest()

    def lemma_of(self, surface: str) -> str | None:
        """Return the single lemma for ``surface`` when unambiguous, else None.

        ``None`` covers both the ambiguous case (>1 matching lemma) and the
        unknown case (0 matching lemmas) --- in neither case may a caller treat
        the result as a resolved lemma.
        """
        matches = self.analyze(surface)
        if len(matches) == 1:
            return matches[0]
        return None


def _entries_for(lemmas: Iterable[str] | None) -> tuple[MorphEntry, ...]:
    """Build the :class:`MorphEntry` list for ``lemmas``.

    ``lemmas=None`` defaults to the closed known-head inventory.  Caller-supplied
    lemmas must themselves be known heads (the only lemmas M1 can resolve a
    morph_class for without a flag); :func:`head_entry` raises ``KeyError`` on an
    unknown lemma --- membership is never guessed.
    """
    names = sorted(_HEADS) if lemmas is None else sorted(set(lemmas))
    return tuple(head_entry(name) for name in names)


def _build(lemmas: tuple[str, ...] | None) -> LemmaIndex:
    """Pure builder shared by the public (memoized) and explicit entry points."""
    entries = _entries_for(lemmas)

    reverse: dict[str, set[str]] = {}
    for entry in entries:
        # Enumerate the FULL paradigm: every reference_v1 case, both numbers.
        forms = generate_forms(entry, numbers=(MorphNumber.SG, MorphNumber.PL))
        for form in forms:
            # Skip forms M1 declines to commit to (fail-loud "unsupported" with
            # an empty surface) --- they are not real outputs to index.
            if form.certainty != "deterministic" or not form.surface:
                continue
            reverse.setdefault(_normalize(form.surface), set()).add(form.lemma)

    frozen = {surface: tuple(sorted(ls)) for surface, ls in reverse.items()}
    return LemmaIndex(_map=frozen, lemmas=tuple(e.lemma for e in entries))


@lru_cache(maxsize=None)
def _build_default() -> LemmaIndex:
    return _build(None)


def build_lemma_index(lemmas: Iterable[str] | None = None) -> LemmaIndex:
    """Build a :class:`LemmaIndex` over ``lemmas`` (default: known-head inventory).

    For each lemma, every inflected form M1 generates (full ``reference_v1``
    paradigm, sg + pl) is indexed ``normalized_surface -> sorted lemmas``.

    The default (``lemmas=None``) builds over the closed known-head inventory and
    is memoized (the inventory + M1 generation are both immutable, so the index
    is a singleton).  An explicit ``lemmas`` argument always builds fresh.

    Caller-supplied lemmas MUST be known heads; an unknown lemma raises
    ``KeyError`` from :func:`head_entry` rather than being silently inflected
    with a guessed morph_class.
    """
    if lemmas is None:
        return _build_default()
    return _build(tuple(sorted(set(lemmas))))


__all__ = ["LemmaIndex", "build_lemma_index"]
